controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    gripper_action_controller:
      type: position_controllers/GripperActionController



gripper_action_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    joint: gripper_joint1
    max_effort: 0.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001