controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_action_controller:
    #   type: gripper_controllers/GripperActionController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - gripper_joint1
      - gripper_joint2




    command_interfaces:
      - position
      - velocity
      

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    open_loop_control: true

# gripper_action_controller:
#   ros__parameters:
    
#     allow_stalling: false
#     goal_tolerance: 0.01
#     joint: gripper_joint1
#     max_effort: 0.0
#     stall_timeout: 1.0
#     stall_velocity_threshold: 0.001
    