controller_manager:
  ros__parameters:
    update_rate: 30


    joint_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_gripper_controller:
  ros__parameters:
    joints:
      - gripper_joint1
      - gripper_joint2
      - gripper_joint3


    command_interfaces:
      - position
      - velocity
      

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    open_loop_control: true
    